const ADD_TOAST = 'ADD_TOAST';
const REMOVE_TOAST = 'REMOVE_TOAST';

const IS_USER_AUTHENTICATED = 'IS_AUTHENTICATED';

const PAGE_ITEMS_FETCH_INIT = 'ITEMS_FETCH_INIT';
const PAGE_ITEMS_FETCH_SUCCESS = 'ITEMS_FETCH_SUCCESS';
const PAGE_ITEMS_FETCH_FAILURE = 'ITEMS_FETCH_FAILURE';
const UPDATE_PAGE_ITEM = 'UPDATE_PAGE_ITEM';
const ADD_PAGE_ITEM = 'ADD_PAGE_ITEM';
const REMOVE_PAGE_ITEM = 'REMOVE_PAGE_ITEM';

const SAVE_USER_RECIPE = 'SAVE_USER_RECIPE';
const REMOVE_USER_RECIPE = 'REMOVE_USER_RECIPE';
const DELETE_USER_RECIPE = 'DELETE_USER_RECIPE';
const ADD_RECIPE_FILTER = 'ADD_RECIPE_FILTER';
const REMOVE_RECIPE_FILTER = 'REMOVE_RECIPE_FILTER';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

const ADD_RECIPE_TO_PREPARE = 'PREPARE_RECIPE';
const REMOVE_PREPARED_RECIPE = 'REMOVE_PREPARED_RECIPE_ID';

const SAVE_FRIDGE_ITEM = 'SAVE_FRIDGE_ITEM';
const DELETE_FRIDGE_ITEM = 'DELETE_FRIDGE_ITEM';

const USER_RECIPES_FETCH_SUCCESS = 'USER_RECIPES_SUCCESS';
const USER_RECIPES_FETCH_FAILURE = 'USER_RECIPES_FAILURE';
const USER_RECIPES_FETCH_INIT = 'USER_RECIPES_INIT';

const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';
const MODAL_ITEMS_FETCH_INIT = 'MODAL_ITEMS_FETCH_INIT';
const MODAL_ITEMS_FETCH_FAILURE = 'MODAL_ITEMS_FETCH_FAILURE';
const MODAL_ITEMS_FETCH_SUCCESS = 'MODAL_ITEMS_FETCH_SUCCESS';

export {
  ADD_TOAST,
  REMOVE_TOAST,
  IS_USER_AUTHENTICATED,
  PAGE_ITEMS_FETCH_INIT,
  PAGE_ITEMS_FETCH_SUCCESS,
  PAGE_ITEMS_FETCH_FAILURE,
  UPDATE_PAGE_ITEM,
  SAVE_USER_RECIPE,
  DELETE_USER_RECIPE,
  REMOVE_USER_RECIPE,
  ADD_RECIPE_TO_PREPARE,
  REMOVE_PREPARED_RECIPE,
  ADD_RECIPE_FILTER,
  REMOVE_RECIPE_FILTER,
  SET_CURRENT_PAGE,
  USER_RECIPES_FETCH_FAILURE,
  USER_RECIPES_FETCH_SUCCESS,
  USER_RECIPES_FETCH_INIT,
  ADD_PAGE_ITEM,
  REMOVE_PAGE_ITEM,
  SAVE_FRIDGE_ITEM,
  DELETE_FRIDGE_ITEM,
  SHOW_MODAL,
  HIDE_MODAL,
  MODAL_ITEMS_FETCH_INIT,
  MODAL_ITEMS_FETCH_FAILURE,
  MODAL_ITEMS_FETCH_SUCCESS
};
